### ISSUE TITLE
Are you still accepting PR's?

### ISSUE THREAD

**Issue by NoScopie** [PharkMillups/beautiful-docs#107]
Are you still accepting PR's and maintaining this repo? If you're short on time I would be happy to help you.

**Comment by PharkMillups** [comment]
Hey there. I'm still accepting PRs but I've been pressed for time of late and have been slacking. Sorry. I'm hoping to clean up the existing ones in the coming weeks. Thanks for offering to help. Let me blow through the existing PRs and I'll get back to you.

**Comment by huei90** [comment]
Agree with that. 
Seems it's an active docs, keep updating it or looking help from some collaborators and maintainers.
