### ISSUE TITLE
Do you want to go on the awesome list?

### ISSUE THREAD

**Issue by dthree** [PharkMillups/beautiful-docs#116]
@PharkMillups love this list! Enough that I made a PR to get it onto the official awesome list:

https://github.com/sindresorhus/awesome/pull/313

To get on there, the page needs a few changes. I can make these changes for you, I just want to check with you first if you care. If not, I can just close that PR.

Happy documenting!

**Comment by PharkMillups** [comment]
Hey dc, 

Thanks for offering to make this happen but I think I'll pass on this for now. 

Mark

**Comment by dthree** [comment]
K no probs :)
